### DISCUSSION TITLE
Add distinction between active and inactive state, again

### DISCUSSION THREAD

**Discussion by Speravir** [uBlockOrigin/uBlock-issues#2409] [Q&A] [answered]
The bug report template is too restrictive for this, hence here.

In the very early times of uBlock I had asked for this and after being added by altering the label I used this for years in `userChrome.css`:
```css
#ublock0_raymondhill_net-browser-action {/* active */
	list-style-image: url("…") !important;
}
#ublock0_raymondhill_net-browser-action[label="uBlock Origin (off)"] {/* inactive */
	list-style-image: url("…") !important;
}
```
I do not know anymore, whether it was Raymond or the other guy whose name I’ve forgotten, who added the different label for the inactive state, but it worked fine all the time.  
Now, with Firefox 108 the ID for the symbol changed (`browser-action` to `BAP`) and on investigating I noticed that the label is not changed anymore, so the symbol does not change when I set the addon into inactive state. I must admit that I had not set the addon to inactive for quite a while, so it maybe the change happened in an earlier version before the recent uBO 1.45.2.

So, please, re-add some kind of distinction between active and inactive addon state. I does not necessarily need to be the label, e.g. something like a `data-state` would be sufficient enough, as well.
