### DISCUSSION TITLE
Any way to disable Picker's fade when investigating mobile sites on desktop?

### DISCUSSION THREAD

**Discussion by u-RraaLL** [uBlockOrigin/uBlock-issues#2486] [Q&A] [answered]
When investigating mobile sites via FF's Responsive Design Mode, the Picker's window auto fades by itself. This makes it very difficult to write/test filters.

The box seems to only reactivate when approached from the left or the bottom. But it'll keep hiding.

For now I usually Inspect the box and disable opacity and animation properties for Picker's `aside`. It works, but doing the same for every Picker instance gets annoying really fast.

Is there any way of disabling the fade permanently?

**Comment by krystian3w** [comment]
If you have access to `userContent.css` and `about:config` (or `prefs.js`) [e.g. both don't blocked by Corporation/Company on non-private PC/smartphone) then you can test:

```css
html.paused aside:has(.CodeMirror-focused, .cm-focused) {
    opacity: 1 !important
}
```

later:

```css
html.paused aside:focus-within {
    opacity: 1 !important
}
```

https://github.com/uBlockOrigin/uBlock-issues/issues/55#issuecomment-1282002311

in about:config to change are/is:

`toolkit.legacyUserProfileCustomizations.stylesheets` - for activate `userContent.css` (no longer enabled in Firefox 69+) [I have no information on whether smartphones used to tolerate this file].
`layout.css.has-selector.enabled` - if `:focus-within` totally fail.

Also possible manually inject these CSS until picker exist in DOM tree (PC/smartphone with limitations other than remote debugging).

I don't think so about inject scriptlet to Picker after gorhill allow inject these everywhere e.g. in logger I see injection on "`about:blank`".

---

At worst, you need to read up on how to Beta-Nightly install a modified add-on (signed/unsigned) assuming that there won't be much difference in how the site behaves in a newer browser than the stable one.

**Reply by u-RraaLL** [reply]
Yea, I was thinking about using userContent.css, but I'd probably use this instead:

```css
#ublock0-epicker.mobile.paused aside {
    opacity: 1 !important;
    animation-duration: unset !important;
}
```
I just think an advanced setting to disable picker's fade would be useful, but I guess I'll make do with this instead.

I also discovered that Picker will behave better if I turn of touch simulation in Responsive Design Mode.

Anyway, thanks for linking the issue too.
