### DISCUSSION TITLE
Overextended source URL button in the code viewer

### DISCUSSION THREAD

**Discussion by partingscientist** [uBlockOrigin/uBlock-issues#2735] [General] [answered]
<details>

<summary>The source URL button's clickable area in the code viewer seems overextended</summary>

![cm](https://github.com/uBlockOrigin/uBlock-issues/assets/115052854/08dae5e2-3e1c-4819-a803-92630385b0a1)

</details>

**Comment by krystian3w** [comment]
Bad can works part of flexbox:

```css
.cm-search-widget > * {
  flex-grow: 1;
}
```

**Reply by krystian3w** [reply]
Suggested is change to "0" for links.

**Reply by partingscientist** [reply]
Using 0 will not center the linter widget, unfortunately.

**Reply by krystian3w** [reply]
Check this out:

```css
.cm-search-widget > a.sourceURL {
  flex-grow: 0;
}
```

More on center may need add too:

```css
.cm-search-widget > .cm-linter-widget {
  flex-grow: 2;
}
```
