### ISSUE TITLE
Add info to the wiki on how to make "$removeparam" entries tokenizable

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1779]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Occasionally, I've heard from uAssets team members that `$removeparam` entries must be tokenizable, for instance at https://github.com/DandelionSprout/adfilt/discussions/163#discussioncomment-1533423

This has given me some problems, since I've slowly realised that I have no idea at all how computer tokens work like, nor do I know of any example cases either. The only tokens I'm familiar with at the time of writing, are casino table tokens.

So I figured that https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam would've had more info about making its entries tokenizable, but it doesn't mention the concept at all. So at the time of writing, I am considerably confused as to which RegEx entries that are tokenizable and which ones that aren't, and I would've very much loved for some examples to be added to that wiki page.

### A specific URL where the issue occurs

https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt

### Steps to Reproduce

1) Be unsure what "tokenizable" means as an English word or how it affects adblockers through `$removeparam`
2) Go to https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam
3) See that there's no additional info about it.

### Expected behavior

The term "tokenizable" is explained on the uBO wiki, since tokenizable entries are considered to speed up uBO performance.

### Actual behavior

The term "tokenizable" doesn't seem to be explained on the uBO wiki that I'm aware of.

### Configuration

<details>

```yaml
browserFlavor: ublock webext devbuild chromium user_stylesheet
browserVersion: 95
extensionId: cgbcahbpdhpcegmbfconppldiemgcoii
extensionName: uBlock Origin
extensionVersion: 1.38.7b5
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
modifiedHiddenSettings: 
  autoCommentFilterTemplate: {{url}} ({{date}})
listset: 
  removed: 
    easyprivacy: null
    plowe-0: null
    ublock-privacy: null
  added: 
    https://assets.windscribe.com/custom_blocklists/clickbait.txt: 
      filters used/total: 252 / 252
      updated last/next (days): -3.01 / 1.99
    https://easylist-downloads.adblockplus.org/fanboy-notifications.txt: 
      filters used/total: 630 / 630
      updated last/next (days): -0.05 / 0.95
    https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/push-notifications.txt: 
      filters used/total: 802 / 894
      updated last/next (days): -3.01 / 1.99
    https://raw.githubusercontent.com/DandelionSprout/Swedish-List-for-Adblock-Plus/main/Swedish%20List%20for%20Adblock%20Plus.txt: 
      filters used/total: 2797 / 2799
      updated last/next (days): -1.93 / 4.07
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiCartoonHipsterList.txt: 
      filters used/total: 7005 / 7009
      updated last/next (days): -0.4 / 2.6
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/MeWe%20Pink%20Theme.txt: 
      filters used/total: 42 / 42
      updated last/next (days): -1.05 / 5.95
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/a.txt: 
      filters used/total: 49162 / 49515
      updated last/next (days): -0.05 / 0.95
    https://raw.githubusercontent.com/MassMove/AttackVectors/master/LocalJournals/fake-local-journals-list.txt: 
      filters used/total: 1083 / 1083
      updated last/next (days): -3.01 / 1.99
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 
      filters used/total: 7253 / 7254
      updated last/next (days): -1.93 / 0.07
    https://raw.githubusercontent.com/llacb47/miscfilters/master/antipaywall.txt: 
      filters used/total: 1873 / 1873
      updated last/next (days): -1.93 / 1.07
    FIN-0: 
      filters used/total: 1422 / 1424
      updated last/next (days): -0.07 / 3.93
    LTU-0: 
      filters used/total: 1151 / 1152
      updated last/next (days): -1.05 / 5.95
    adguard-generic: 
      filters used/total: 59393 / 60356
      updated last/next (days): -0.07 / 3.93
    adguard-mobile: 
      filters used/total: 6645 / 6694
      updated last/next (days): -0.06 / 3.94
    block-lan: 
      filters used/total: 43 / 43
      updated last/next (days): -8.08 / 21.92
    curben-phishing: 
      filters used/total: 19291 / 19292
      updated last/next (days): -0.05 / 0.95
    curben-pup: 
      filters used/total: 400 / 402
      updated last/next (days): -0.05 / 0.95
    ublock-annoyances: 
      filters used/total: 4189 / 4273
      updated last/next (days): -0.06 / 3.94
  default: 
    NOR-0: 
      filters used/total: 2225 / 2264
      updated last/next (days): -0.05 / 0.95
    easylist: 
      filters used/total: 55687 / 59763
      updated last/next (days): -0.06 / 3.94
    ublock-abuse: 
      filters used/total: 67 / 67
      updated last/next (days): -0.06 / 3.94
    ublock-badware: 
      filters used/total: 2382 / 3064
      updated last/next (days): -0.06 / 3.94
    ublock-filters: 
      filters used/total: 26345 / 29089
      updated last/next (days): -0.06 / 3.94
    ublock-unbreak: 
      filters used/total: 1623 / 1686
      updated last/next (days): -0.06 / 3.94
    urlhaus-1: 
      filters used/total: 17228 / 17268
      updated last/next (days): -0.05 / 0.95
filterset: [array of 9 redacted]

```
</details>
