### ISSUE TITLE
Unremovable custom filter lists in uBO 1.33.2-1.38.7b15

### ISSUE THREAD

**Issue by u-RraaLL** [uBlockOrigin/uBlock-issues#1803]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

In uBO 1.33.2+ if you:

1. Restore from backup settings that have an imported/custom filter list added and then try deleting it later (at any point), OR:
2. Add a new custom list and delete it **in the same browser session**...

the list will always come back after restarting the browser (albeit disabled).

### A specific URL where the issue occurs

/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Install uBO 1.33.2 or latter.
2. Go to filter lists and add a custom list, e.g. `https://github.com/DandelionSprout/adfilt/raw/master/WikiaPureBrowsingExperience.txt`.
3. Delete it, apply.
4. Restart browser.
5. Go to filter lists, see the (now disabled) list again.
6. Repeat 3-5 to infinity ;)

Alternative:

1. Install uBO 1.33.2 or latter.
2. Go to Settings and restore backup that has a custom list.
3. Restart browser (or not).
3. Go to filter lists, delete the custom list, apply.
4. Restart browser.
5. Go to filter lists, see the (now disabled) list again.
6. Repeat 4-6 to infinity ;)

The only way to remove such custom list (other than resetting to defaults) is to:

1. Delete the list, apply.
2. Go to settings, backup.
3. Restore from backup.

### Expected behavior

Custom lists stay gone upon deletion.

### Actual behavior

They don't.

The issue doesn't occur on 1.31-1.33. Starts with 1.33.2 and is reproducible up until the latest dev build (1.38.7b15). At least on the ones I've tried - and I've tried on plenty.

### Configuration

<details>

```yaml
browserFlavor: ublock webext devbuild firefox user_stylesheet html_filtering mozilla
browserVersion: 93
extensionName: uBlock Origin
extensionVersion: 1.38.7b15
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  firewallPaneMinimized: false
modifiedHiddenSettings: 
  blockingProfiles: 11111/#222 11010/#C0F 11001/#00F 00001
listset (total-discarded, last updated): 
  added: 
    block-lan: 44-0, now
  default: 
    ublock-filters: 30160-30, now
    ublock-badware: 3167-1, now
    ublock-privacy: 178-0, now
    ublock-abuse: 67-0, now
    ublock-unbreak: 1697-0, now
    easylist: 60341-517, now
    easyprivacy: 25471-209, now
    urlhaus-1: 9085-0, now
    plowe-0: 3675-2, now
filterset: [array of 287 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 98 redacted]

```
</details>
