### ISSUE TITLE
Blue color of large power button leaks to eraser, padlock, and refresh icons in 1.41.x  when using the old popup panel

### ISSUE THREAD

**Issue by otksm** [uBlockOrigin/uBlock-issues#1996]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I understand the old popup panel may be under maintenance mode/unsupported so if anything this is more of a FYI. Feel free to close this as invalid/wonfix.

### A specific URL where the issue occurs

_N/A_

### Steps to Reproduce

1. Check the "I am an advanced user" option in uBO's dashboard.
2. Set `uiFlavor` to classic in advanced settings.
3. Restart Firefox.
4. Click somewhere on the global/local column to make the eraser, padlock, and refresh icons appear.

### Expected behavior

Eraser, padlock, and refresh icons have the same color as they did in 1.40.8 or before.

### Actual behavior

Eraser, padlock, and refresh icons were all blue in color. This only happens when I am using the old popup panel. I currently use the following css code in `userContent.css` to override this behavior.

```css
@-moz-document url-prefix("moz-extension://[your-ubo-webext-uuid]/popup.html") {
#rulesetTools > span {
	background-color: hsla(60, 100%, 95%, 1) !important;
	fill: hsla(261, 53%, 15%, 0.5) !important;
}
#refresh {
	background-color: hsla(60, 100%, 95%, 1) !important;
	fill: hsla(261, 53%, 15%, 0.5) !important;
}
```

### uBlock Origin version

1.41.6

### Browser name and version

Firefox 97.0

### Operating System and version

_N/A_
