### ISSUE TITLE
Site styles break the uBo iframes #3

### ISSUE THREAD

**Issue by Lairub** [uBlockOrigin/uBlock-issues#2098]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Few real pages use `transform: scale(0)` to hide uneded elements like iframes due match `html > :not(body)`:

```css
dialog, video, audio, embed, object, html > :not(body[gdF5]),
body > :not(header[R], h1[ex], div[wy], details[__details], footer[MI], noscript) {
            display: none !important;
            transform: scale(0) !important;
            filter: opacity(0) !important;
}
```
```css         
dialog, audio, embed, object, canvas, fieldset,
form, select, option, input, pre,
html > :not(body),
body > :not(h1, aside, header, main, footer, div.Xd, noscript) {
            display: none !important;
            transform: scale(0) !important;
            filter: opacity(0) !important;
 }
```

#987 / #2075 

### A specific URL where the issue occurs

`mycinema.pro` <br> `mycinema.pro/support.html`

### Steps to Reproduce

1. Open page 
2. Try use picker/zapper/DOM inspector

### Expected behavior

Protect all

### Actual behavior

No protected all

### uBlock Origin version

1.42.5b2

### Browser name and version

Firefox 101

### Operating System and version

Windows 10
