### ISSUE TITLE
Missing tooltips?

### ISSUE THREAD

**Issue by TsukiZero** [uBlockOrigin/uBlock-issues#2106]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

![image](https://user-images.githubusercontent.com/78157224/167256108-47ee706f-5860-4b90-9f2d-ac3857f933e5.png)
"Disable tooltips" is unchecked, this happens only on "Auto" and "Dark" Themes

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

Just hover the tooltip

### Expected behavior

Seeing the tooltip

### Actual behavior

Tooltip's text is white as well as its background, when the tooltip's text should have been white but on a dark background.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 82828
  cosmetic: 43399
  scriptlet: 16897
  html: 647
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 416-0, 9h.22m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 9h.21m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 9h.20m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1032-0, 5d.21h.56m
  default: 
    user-filters: 409-8, never
    ublock-filters: 31573-103, 1d.11h.28m
    ublock-badware: 4153-3, 1d.11h.27m
    ublock-privacy: 217-0, 11d.17h.59m
    ublock-abuse: 74-4, 11d.17h.58m
    ublock-unbreak: 1789-0, 1d.11h.26m
    easylist: 66425-530, 1d.11h.25m
    easyprivacy: 26943-914, 1d.11h.24m
    urlhaus-1: 8573-0, 9h.23m
    plowe-0: 3679-5, 11d.9h.52m
    ublock-quick-fixes: 213-0, 9h.19m
filterset (user): [array of 409 redacted]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-csp-reports: * true
hostRuleset: 
  added: [array of 1 redacted]
urlRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  showIconBadge: false
modifiedHiddenSettings: 
  uiFlavor: classic
supportStats: 
  allReadyAfter: 666 ms (selfie)
  maxAssetCacheWait: 535 ms
```
</details>

**Comment by gorhill** [comment]
You are using the _classic_ popup panel, it's not supported anymore.

**Comment by TsukiZero** [comment]
But the Classic is still more compact and less "Help me I'm a blind person who can't see a thing". Seriously, why deprecate the better UI like that?

**Comment by gorhill** [comment]
Deprecation of the old popup panel was announced almost two years ago. This is not something to be discussed -- I happen to be the one having to suffer the workload of maintaining old code. I will remove support for the next release, this will prevent future issues from being opened about it.

**Comment by TsukiZero** [comment]
Good, I'll stop updating ublock then! And maybe look for an alternative that makes better UI

**Comment by gorhill** [comment]
> NEVER force redesigns without extensive research

Through my experience with this project, I learned that you can't please everyone at once.

A lot of people also disliked the old popup panel even before the new one came into existence, and which came into being without the help of an actual designer and which also suffered obvious shortcomings -- such as the padlock/revert buttons not being available to per-site switches without expanding the left pane (which in turn made the popup panel much larger than what it is now if one wants to use per-site switches without dynamic filtering); the hidden "buttons" to expand/collapse the overview pane.

Also the old popup panel was not showing the current site, which the new one does, and which is helpful when it comes to use the power button or per-site switches. The power button and per-site switches are now all logically closer together and closer to padlock/revert buttons. This also helps to protect against [IDN attacks](https://www.аррӏе.com/) without having to expand the left pane of the popup panel.

The new popup panel also makes it much easier to pick different level of details, even allowing it to show only the power button for those who prefer very small popup panel with no need to fiddle with uBO -- so it is actually more configurable than the previous one.

In any case, as said I am aware not everybody can be pleased, so in the end I go with what **I** like (I am the one working on this for my own fun), while taking feedback into account, and as [per reception](https://github.com/uBlockOrigin/uBlock-issues/issues/1027) (146 yeas, 2 nays), you would be one of the few preferring the old one.

---

> I'll stop updating ublock then! And maybe look for an alternative that makes better UI.

To me such statement is equivalent to announcing you are going to hit your thumb with a hammer to protest my decision. Be my guess. I myself have invited people to look for something else when in the end it's obvious they are unhappy with how I maintain uBO.

Fun fact: all the other popular blockers have larger popup panel size (px, English version):

- AdGuard: 320 x 600
- AdBlock: 320 x 431
- Adblock Plus: 340 x 553
- Ghostery: 580 x 516
- uBO: 252 x 424 (631 x 424+ when expanded)

And this with per-site switches visible in uBO, something other blockers do not have. When expanded, uBO is larger, but then other blockers do not have dynamic filtering integrated with list blocking, so there is no point to compare the expanded popup panel with blockers not supporting the same features -- but if popup panel size is your top criteria, looks like AdBlock will be your preferred candidate.

---

> less "Help me I'm a blind person who can't see a thing".
> people are given the ability to customize the look of the browser

You can change [popup panel font size](https://github.com/gorhill/uBlock/wiki/Advanced-settings#popupfontsize) in advanced setting, and even redefine some CSS variables through [`uiStyles`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#uistyles) -- yet another demonstration of how much more configurable uBO is compared to other blockers, so lecturing about lack of configuration options in uBO is dubious.

**Comment by TsukiZero** [comment]
Still, crap design is crap design. And knowing your mentality, I'm certain you'll remove uiStyles next.

**Comment by TsukiZero** [comment]
> Guess it's too late now but FWIW this seem to work as a hotfix if you apply it to your own `userContent.css`:
> 
> ```css
> @-moz-document url("moz-extension://[your-ubo-webext-uuid]/popup.html") {
> :root.dark > body > #panes > .tooltipContainer > #tooltip {
> 	color: black !important;
> 	}
> }
> ```
Also doable via uiStyle by adding `--bg-tooltip: black;`.
Which I had to View Sources to find.

**Comment by JohnyP36** [comment]
@gorhill Without repeating the thinks you and the people above stated in the conversation I personal like the old UI, but as it will removed i would like to change the new UI. In the wiki it says that in your `advanced settings` you can change the popup menu by changing styles under the option `uiStyles.` However, it didn't work for me to change the size of the power button. 
Is that possible to change yourself or not?

**Comment by TsukiZero** [comment]
> @gorhill Without repeating the thinks you and the people above stated in the conversation I personal like the old UI, but as it will removed i would like to change the new UI. In the wiki it says that in your `advanced settings` you can change the popup menu by changing styles under the option `uiStyles.` However, it didn't work for me to change the size of the power button. Is that possible to change yourself or not?

The wiki doesn't explain, but you NEED to know the source for that. You can access it by bringing up the UI, right clicking in it and clicking "View Page Source". In there you can CTRL + Left Click the Stylesheet links (CSS) to get to the real meat on the bone for the uiStyles. That's how I found how to fix the tooltip myself.

**Comment by JohnyP36** [comment]
@TsukiZero 

> The wiki doesn't explain, but you NEED to know the source for that. You can access it by bringing up the UI, right clicking in it and clicking "View Page Source". In there you can CTRL + Left Click the Stylesheet links (CSS) to get to the real meat on the bone for the uiStyles. That's how I found how to fix the tooltip myself. 

If I do that I got in the following screen ↓

<details><summary>See screenshot</summary>

![image](https://user-images.githubusercontent.com/81161435/179755555-7c08fd31-6907-48ff-ac1c-c981d3ceec77.png)

</details>

I put this in the advanced settings

```css
#main{width: fit-content; min-width: 0px;} 

.fa-icon{padding: 0 0.01em;} 

#hostname{display: none;} 

#switch{font-size: 700%;} 

.toolRibbon{background-color: var(--surface-2); margin-top: 10px;} 

.toolRibbon .tool{font-size: 1.1em; min-width: 25px; fill: var(--ink-4);} 

:root.mobile body[data-ui~="-captions"] .toolRibbon .tool {padding: 0.5em 0;} 

#basicStats{margin: 10px 10px -10px 10px;} 

.itemRibbon{column-gap: 0px; display: flex; background-color: #444; color: #bbb; font-size: smaller; margin: 0; justify-content: center;}
```

###### In advanced settings I put this in one row.
which becomes
```css
#main{width: fit-content; min-width: 0px;} .fa-icon{padding: 0 0.01em;} #hostname{display: none; line-height: 120%;} #switch{font-size: 700%} .toolRibbon{background-color: var(--surface-2); margin-top: 10px;} .toolRibbon .tool{font-size: 1.1em; min-width: 25px; fill: var(--ink-4);} :root.mobile body[data-ui~="-captions"] .toolRibbon .tool{padding: 0.5em 0;} #basicStats{margin: 10px 10px -10px 10px;} .itemRibbon{column-gap: 0px; display: flex; background-color: #444; color: #bbb; font-size: smaller; margin: 0; justify-content: center;}
```

#### But this does not work. 
What did I do wrong?

@gorhill Can you maybe look at this?
