### ISSUE TITLE
Settings ignored as added lists reloaded after Firefox launch in private mode

### ISSUE THREAD

**Issue by mraandtux** [uBlockOrigin/uBlock-issues#2725]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Mind the ***false*** on the "suspendUntilListsAreLoaded" and "autoUpdate" settings. The "added" lists ignores the global setting ("auto update" and "uspend network activity until all filter lists are loaded" were unticked) and reloading from the web after launch.

```
uBlock Origin: 1.50.1b12
Firefox: 115
...
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
  CHN-0: null
 added:
  https://easylist-downloads.adblockplus.org/easylistchina.txt: 22775-89, never
  fanboy-cookiemonster: 47808-228, never
 default:
  user-filters: 149-0, never
  ublock-filters: 34627-55, never
  ublock-badware: 7482-0, never
  ublock-privacy: 464-0, never
  ublock-unbreak: 2102-0, never
  ublock-quick-fixes: 270-5, never
  easylist: 67761-309, never
  easyprivacy: 33394-87, never
filterset (user): [array of 34 redacted]
userSettings:
 autoUpdate: false
 cloudStorageEnabled: true
 cnameUncloakEnabled: false
 showIconBadge: false
 suspendUntilListsAreLoaded: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6783 ms
 maxAssetCacheWait: 324 ms
 unsuspendAfter: 1077 ms
```

### A specific URL where the issue occurs.

N/A

### Steps to Reproduce

1. Open Firefox **in private mode** (`firefox --private`)
2. Add lists outside of the default lists (UBlock, Easylist, Easyprivacy, etc...) , eg locals and annoyances list
3. restart 

### Expected behavior

Non-default lists like CHN-0 and fanboy-cookiemonster will loaded from cache

### Actual behavior

The lists keeps updating everytime I launch my browser in private mode, bypassing the extension's global settings.

### uBO version

1.50.1b12

### Browser name and version

Firefox 115 (both PPA deb and Flatpak)

### Operating System and version

Ubuntu 23.04
