### ISSUE TITLE
kk

### ISSUE THREAD

**Issue by Zeroocooloverride** [uBlockOrigin/uBlock-issues#3405]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

  ublock-privacy: 1305-22, 2h.46m Δ
  ublock-unbreak: 2471-0, 2h.46m Δ
  ublock-quick-fixes: 170-0, 2h.46m Δ
  easylist: 85824-576, 2h.46m Δ
  easyprivacy: 53135-646, 2h.46m Δ
  urlhaus-1: 25255-0, 20h.31m
  plowe-0: 3550-0, 14d.11h.32m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1969 ms
 maxAss

### A specific URL where the issue occurs.

```yaml
ublock-privacy: 1305-22, 2h.46m Δ
  ublock-unbreak: 2471-0, 2h.46m Δ
  ublock-quick-fixes: 170-0, 2h.46m Δ
  easylist: 85824-576, 2h.46m Δ
  easyprivacy: 53135-646, 2h.46m Δ
  urlhaus-1: 25255-0, 20h.31m
  plowe-0: 3550-0, 14d.11h.32m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1969 ms
 maxAss
```

### Steps to Reproduce

  ublock-privacy: 1305-22, 2h.46m Δ
  ublock-unbreak: 2471-0, 2h.46m Δ
  ublock-quick-fixes: 170-0, 2h.46m Δ
  easylist: 85824-576, 2h.46m Δ
  easyprivacy: 53135-646, 2h.46m Δ
  urlhaus-1: 25255-0, 20h.31m
  plowe-0: 3550-0, 14d.11h.32m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1969 ms
 maxAss

### Expected behavior

  ublock-privacy: 1305-22, 2h.46m Δ
  ublock-unbreak: 2471-0, 2h.46m Δ
  ublock-quick-fixes: 170-0, 2h.46m Δ
  easylist: 85824-576, 2h.46m Δ
  easyprivacy: 53135-646, 2h.46m Δ
  urlhaus-1: 25255-0, 20h.31m
  plowe-0: 3550-0, 14d.11h.32m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1969 ms
 maxAss

### Actual behavior

  ublock-privacy: 1305-22, 2h.46m Δ
  ublock-unbreak: 2471-0, 2h.46m Δ
  ublock-quick-fixes: 170-0, 2h.46m Δ
  easylist: 85824-576, 2h.46m Δ
  easyprivacy: 53135-646, 2h.46m Δ
  urlhaus-1: 25255-0, 20h.31m
  plowe-0: 3550-0, 14d.11h.32m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1969 ms
 maxAss

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150740
 cosmetic: 48493
 scriptlet: 22791
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 40391-259, 2h.46m Δ
  ublock-badware: 11579-6, 2h.46m Δ
  ublock-privacy: 1305-22, 2h.46m Δ
  ublock-unbreak: 2471-0, 2h.46m Δ
  ublock-quick-fixes: 170-0, 2h.46m Δ
  easylist: 85824-576, 2h.46m Δ
  easyprivacy: 53135-646, 2h.46m Δ
  urlhaus-1: 25255-0, 20h.31m
  plowe-0: 3550-0, 14d.11h.32m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1969 ms
 maxAssetCacheWait: 652 ms
 cacheBackend: indexedDB
```
</details>
