### ISSUE TITLE
uBO does not unhide nodes no longer matching procedural cosmetic filters

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#341]
### Prerequisites

- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior
- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### Description

e.g. 

```
##.nytc---modal-window---isShown:if-not(.nytc---largepicturemodal---contentBody > .nytc---x---x.nytc---largepicturemodal---xBtn[role="button"])
```
 filter cut to much in uBO on `cooking.nytimes.com`.

### A specific URL where the issue occurs

`https://cooking.nytimes.com/recipes/1018016-pot-roast`
`https://cooking.nytimes.com/recipes/1650-italian-pot-roast-stracotto`

https://github.com/uBlockOrigin/uAssets/issues/3708
https://github.com/AdguardTeam/AdguardFilters/issues/24339

```css
cooking.nytimes.com#$#html.nytc---modal-window---noScroll { overflow: visible!important; }
cooking.nytimes.com#$#body.nytc---modal-window---noScroll { overflow: visible!important; }
cooking.nytimes.com##.nytc---modal-window---isShown:not(:has(.nytc---largepicturemodal---contentBody > .nytc---x---x.nytc---largepicturemodal---xBtn[role="button"]))
```

uBO rewrite last filter:

```
cooking.nytimes.com##.nytc---modal-window---isShown:if-not(.nytc---largepicturemodal---contentBody > .nytc---x---x.nytc---largepicturemodal---xBtn[role="button"])
```

### Steps to Reproduce

1. Open website
2. block pop-up with AdGuard rewrite filter
3. button (link) login no works - no open Window login with ":x:" button.

### Expected behavior:

filter works same as in AdGuard with `:if-not()` construction on uBO.

### Actual behavior:

filter no works same as in AdGuard with `:if-not()` construction on uBO.

### Your environment

* uBlock Origin version: uBO 1.17.4
* Browser Name and version: Firefox 64 x64
* Operating System and version: Windows 7 Pro x64
