### ISSUE TITLE
Website glitch element picker

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#419]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

broken size and fixed position for element picker

### A specific URL where the issue occurs

`http://muzykabezkabli.pl/`

### Steps to Reproduce

1. Open website
2. Try block something by element picker
3. elelement picker now is glitched

### Expected behavior:

Possible fix?

### Actual behavior:

glitched by CSS3 tranformations?

### Your environment

* uBlock Origin version: uBO 1.18.4
* Browser Name and version: Firefox 56
* Operating System and version: Windows 7

**Comment by krystian3w** [comment]
`https://web.archive.org/web/20190212164309/http://muzykabezkabli.pl/`

**Comment by uBlock-user** [comment]
The only glitch I see is the position of the red target selector, other than that everything else is fine.

**Comment by uBlock-user** [comment]
The glitch in the screenshot is specific to Firefox.

**Comment by krystian3w** [comment]
So no reproduced on Chromium?

**Comment by uBlock-user** [comment]
> So no reproduced on Chromium?

Yes, I cannot reproduce the glitch in the picture on Chromium.

**Comment by krystian3w** [comment]
`<html` `style="transform: scale(0.895333, 0.895333);"` `>` on mother website I found.

**Comment by krystian3w** [comment]
On chromium website use:

`<html `style="zoom: 0.895333;"` `>`, so possible reproduce in Chromium with better demo.

**Comment by krystian3w** [comment]
For me this is very bad CSS Media Query use method:

`http://www.muzykabezkabli.pl/css/zoom.css`

```css
@media screen and (min-width: 1516px) {

	html {
		zoom: 1;
		-ms-zoom: 1;
		-webkit-zoom: 1;
		
	}

}


@media screen and (max-width: 1515px) {

	html {
		/* zoom: 0.95; */
		-ms-zoom: 0.95;
		-webkit-zoom: 0.95;
		-moz-transform: scale(0.95,0.95);
		-moz-transform-origin: left top;
	}

}

@media screen and (max-width: 1440px) {

	html {
		/* zoom: 0.90; */
		-ms-zoom: 0.90;
		-webkit-zoom: 0.90;
		-moz-transform: scale(0.90,0.90);
		-moz-transform-origin: left top;
	}

}

@media screen and (max-width: 1365px) {

	html {
		/* zoom: 0.85; */
		-ms-zoom: 0.85;
		-webkit-zoom: 0.85;
		-moz-transform: scale(0.85,0.85);
		-moz-transform-origin: left top;
	}

}

@media screen and (max-width: 1284px) {

	html {
		zoom: 0.80;
		-ms-zoom: 0.80;
		-webkit-zoom: 0.80;
		-moz-transform: scale(0.80,0.80);
		-moz-transform-origin: left top;
	}

}

@media screen and (max-width: 1224px) {

	html {
		zoom: 0.75;
		-ms-zoom: 0.75;
		-webkit-zoom: 0.75;
		-moz-transform: scale(0.75,0.75);
		-moz-transform-origin: left top;
	}

}

@media screen and (max-width: 1138px) {

	html {
		zoom: 0.70;
		-ms-zoom: 0.70;
		-webkit-zoom: 0.70;
		-moz-transform: scale(0.70,0.70);
		-moz-transform-origin: left top;
	}

}

@media screen and (max-width: 1067px) {

	html {
		zoom: 0.65;
		-ms-zoom: 0.65;
		-webkit-zoom: 0.65;
		-moz-transform: scale(0.65,0.65);
		-moz-transform-origin: left top;
	}

}

@media screen and (max-width: 1007px) {

	html {
		zoom: 0.60;
		-ms-zoom: 0.60;
		-webkit-zoom: 0.60;
		-moz-transform: scale(0.60,0.60);
		-moz-transform-origin: left top;
	}

}
```

No possible better build responsive website...
