### ISSUE TITLE
Block select numbers from logger stats list?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#741]
```css
#loggerStatsDialog .sortedEntries > div > span:first-of-type {
    user-select: none;
}
```

https://caniuse.com/user-select-none
https://caniuse.com/#feat=user-select-none

You could add a switch in the pop-up using JS or in the advanced options (although it's a medium idea there)

![obraz](https://user-images.githubusercontent.com/35370833/65958660-3210f700-e450-11e9-8986-c29642fa1bd1.png) |
--- |
